{
 "title": "Admin-Dashboard",
 "tags": [ "templated" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "flask_server_sinus_2m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "flask_server_sinus_2m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "flask_server_sinus_5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "flask_server_sinus_5m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "flask_server_sinus_10m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "flask_server_sinus_10m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count of running flask server pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count:up1{service=\"flask-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Flask-Server Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{app=\"flask-server\"}"
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alert List",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "count of firing alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Count of Alertmanager Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count:up1{service=\"kube-prometheus-stack-alertmanager\"})"
    }
   ]
  }
 ]
}